commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

capstone/clientphotogallery/models.py
from ast import Delete
import os
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.files.storage import FileSystemStorage
from .storage import CustomFileSystemStorage
from django.conf import settings

# Create your models here.

# Photographers are represented by built-in Django User model
class User(AbstractUser):
    pass

# Clients are represented by simple model because we use simple client identification and authentication as we do not want client to require registration
class Client(models.Model):
    identifier = models.CharField(max_length=150, unique=True)
    email = models.EmailField(blank=True)
    # Attributes for client view gallery selectors
    hideSelected = models.BooleanField(default=False)
    onlySelected = models.BooleanField(default=False)
    
    def __str__(self):
        if self.email:
            return "%s (%s)" % ( self.identifier, self.email)
        else:
            return self.identifier
    @property
    def count_selections(self):
        return self.selections.count()

# Model that represents photographer's gallery. Gallery ID is implemented with UUID field becuase it will be used for unique URL that will be shared with clients
class Gallery(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='galleries')
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    enabled = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)
    password = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return self.title
# We need to write our own handle so that files are uploaded to folder matching gallery id under media folder
def upload_to_gallery(instance, filename):
    # if we're passing Asset instance, then we need access gallery.id
    if hasattr(instance, 'gallery'):
        return '{0}/{1}'.format(instance.gallery.id, filename)
    # if we're passing Gallery instance, then we need to access id
    else:
        return '{0}/{1}'.format(instance.id, filename)

# Pictures are represented with Asset model. Idea is to support other files in gallery, not only images, for example zip files.
class Asset(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='assets')
    file = models.FileField(upload_to=upload_to_gallery, storage=CustomFileSystemStorage)

    def __str__(self):
        return self.file.name
    
    @property
    def count_selected(self):
        return self.selections.count()

    @property
    def get_comments(self):
        return self.selections.exclude(comment__exact='')
    
    @property
    def get_print_count(self):
        return self.selections.aggregate(Sum('print_count'))['print_count__sum'] or 0
    
    @property
    def filename(self):
        return os.path.basename(self.file.name)

# Model Selections represents client picture selections within galleries. Each selection is linked to picture, has desired print count and optional comments
class Selection(models.Model):
    asset = models.ForeignKey(Asset,on_delete=models.CASCADE, related_name='selections' )
    client = models.ForeignKey(Client,on_delete=models.CASCADE, related_name='selections' )
    print_count = models.PositiveIntegerField(default=1)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
       

    def serialize(self):
        return {
            "id": self.id,
            "asset": self.asset.id,
            "client": self.client.identifier,
            "coment": self.comment           
        }

# special handlers when the picture is removed from gallery or whole gallery is removed, we need to ensure that file(s) in the gallery media folder is removed also.
@receiver(post_delete, sender=Gallery)
def gallery_post_delete_handler(sender, **kwargs):
    gallery = kwargs['instance']
    fs = FileSystemStorage()
    dir_path = os.path.join(settings.MEDIA_ROOT, str(gallery.id))

    if fs.exists(dir_path):
        files_to_remove = fs.listdir(dir_path)[1]
 
        for file in files_to_remove:
            fs.delete(os.path.join(dir_path, file))
 
        fs.delete(dir_path)

@receiver(post_delete, sender=Asset)
def gallery_post_delete_handler(sender, **kwargs):
    asset = kwargs['instance']
    storage, name = asset.file.storage, asset.file.name
    storage.delete(name)

capstone/clientphotogallery/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Gallery, User

class GalleryCreateForm(forms.ModelForm):
    file_field = forms.FileField(label='Upload files', required=False, widget=forms.ClearableFileInput(attrs={'multiple': True})) 
    class Meta:
        model = Gallery
        fields = ['title','description','password','enabled']

class GalleryEditForm(forms.ModelForm):
    file_field = forms.FileField(label='Upload files', required=False, widget=forms.ClearableFileInput(attrs={'multiple': True})) 
    class Meta:
        model = Gallery
        fields = ['title','description','password','enabled', 'archived']        

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User  
        

capstone/clientphotogallery/views.py
from multiprocessing import context
import re, uuid, json
from xml.dom.minidom import Identified
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied, ValidationError
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.views import LoginView
from django.views.decorators.csrf import ensure_csrf_cookie

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import User, Client, Gallery, Asset, Selection, upload_to_gallery
from django.db.models import Count
from django.db import transaction
from .forms import GalleryCreateForm, GalleryEditForm, RegisterForm
from django.http import JsonResponse


def index(request):
    return render(request, "clientphotogallery/index.html")

class UserIsOwner(UserPassesTestMixin):
    def get_gallery(self):
        return get_object_or_404(Gallery,pk=self.kwargs.get('pk'))

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_gallery().owner
        else:
            raise PermissionDenied('You must be owner of gallery to edit')

# CBV Photographer Login View
class UserLoginView(LoginView):
    template_name= 'clientphotogallery/login.html'
    next_page = 'list'

# CBV Photographer Register View
class UserRegisterView(CreateView):
    template_name = 'clientphotogallery/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('list')
            
    def form_valid(self, form):
        to_return = super().form_valid(form)

        user = authenticate(
            username = form.cleaned_data["username"],
            password = form.cleaned_data["password1"]
        )
        login(self.request, user)
        return to_return
# CBV Gallery List View is main view on Dashboard. All galleries of logged in photographer are displayed together will list of client selections
class GalleryListVew(LoginRequiredMixin,ListView):
    login_url = '/dashboard/login/'
    template_name='clientphotogallery/dashboard.html'
    context_object_name='galleries'

    # Gallery queryset returns only galleries for which logged in user is owner, we also add total number of selections to the context data
    def get_queryset(self):
        queryset = Gallery.objects.filter(owner=self.request.user).annotate(count_selected=Count('assets__selections'))
        return queryset

    # Selections queryset is added to current context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['selections'] = Selection.objects.filter(asset__gallery__owner=self.request.user).values('client__identifier', 'asset__file', 'asset__gallery__title', 'asset__gallery__archived', 'print_count', 'updated','comment')
        return context

# CBV Gallery Client Selections is similar to Gallery List View but it contains only client selections data that will be manipulated further with JS
class GalleryClientSelections(LoginRequiredMixin,ListView):
    login_url = '/dashboard/login/'
    template_name='clientphotogallery/clientselections.html'
    model = Selection
    context_object_name='galleries'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['selections'] = Selection.objects.filter(asset__gallery__owner=self.request.user, asset__gallery__archived=False).values('client__identifier', 'asset__file', 'asset__gallery__title', 'print_count', 'updated','comment')
        return context

# CBV Gallery Detail View generates view with all the assets in the gallery
class GalleryDetailedView(LoginRequiredMixin, UserIsOwner, DetailView):
    login_url = '/dashboard/login/'
    model=Gallery
    template_name='clientphotogallery/gallerydetail.html'
    context_object_name='gallery'

    def get_queryset(self):
        queryset = Gallery.objects.filter(owner=self.request.user).annotate(count_selected=Count('assets__selections'))
        return queryset

# CBV Gallery Create View is simple view for creating new gallery, that handles multi file upload
class GalleryCreateView(LoginRequiredMixin, CreateView):
    login_url = '/dashboard/login/'
    form_class = GalleryCreateForm
    model=Gallery
    template_name='clientphotogallery/gallerycreate.html'
    
    def get_success_url(self):
        return self.request.GET.get('next', reverse_lazy('list'))

    def form_valid(self,form):        
        gallery = form.save(commit=False)
        gallery.owner = self.request.user
        gallery.save()

        with transaction.atomic():
            files = self.request.FILES.getlist('file_field')
            for file in files:
                Asset.objects.create(gallery=gallery, file=file)
        return super().form_valid(form)

# CBV Gallery Edit View for editing exiting gallery, it also supports adding additional files to the gallery
class GalleryEditView(LoginRequiredMixin, UserIsOwner, UpdateView):
    template_name = 'clientphotogallery/galleryedit.html'
    form_class = GalleryEditForm
    model = Gallery

    def get_success_url(self):
        return self.request.GET.get('next', reverse_lazy('list'))

    def form_valid(self,form):        
        gallery = form.save()

        with transaction.atomic():
            files = self.request.FILES.getlist('file_field')
            for file in files:
                if Asset.objects.filter(file=upload_to_gallery(gallery, file)):
                    raise ValidationError('There is already a file with that name on our system')
                else:
                    Asset.objects.create(gallery=gallery, file=file)
        return super().form_valid(form)

# CBV Gallery Delete View
class GalleryDeleteView(LoginRequiredMixin, UserIsOwner, DeleteView):
    login_url = '/dashboard/login/'
    template_name = 'clientphotogallery/gallerydelete.html'
    model = Gallery
    success_url=reverse_lazy('list')

# CBV Gallery Asset Remove View - triggered via the JS fetch from gallerydetail.html asset remove button
class GalleryAssetRemoveView(LoginRequiredMixin, UserIsOwner, DeleteView):
    model = Asset
    
    def get_object(self, queryset=None):
        assetid = self.kwargs['id']
        try:
            asset = self.model.objects.get(id=assetid)
        except asset.DoesNotExist:
            return JsonResponse({"error": "Asset not found."}, status=404)
        return asset
    
    def form_valid(self, request, *args, **kwargs):
        asset = self.get_object()
        asset.delete()
        return JsonResponse({"message": "all ok."}, status=201)

def is_valid_uuid(val):
    try:
        uuid.UUID(str(val))
        return True
    except ValueError:
        return False
# FBV Client Landing View checks if the valid gallery id and either calls the clientgallery view or renders back the landing view
@ensure_csrf_cookie
def ClientLandingView(request):
    if request.method == "POST":
        gallery_id  = request.POST.get('gallery_id',request.GET.get('gallery_id'))
        
        if not is_valid_uuid(gallery_id):
            return render(request, "clientphotogallery/clientlanding.html", { "message":"Gallery removed or not found" })
        
        try:
            gallery = Gallery.objects.get(pk=gallery_id)
            return redirect('clientgalleryview', pk=gallery.id)
        except Gallery.DoesNotExist:
            return render(request, "clientphotogallery/clientlanding.html", { "message":"Gallery removed or not found" })
            
    else:
        return render(request, "clientphotogallery/clientlanding.html")

# FBV Client Gallery View - main client gallery view where we check or set session, if gallery is enabled or archived, check the gallery password and if all ok we render main clientgalleryview.html
@ensure_csrf_cookie
def ClientGalleryView(request, pk=None):
    if (not request.session.get('clientData', False)):
        clientData = {}
    else:
        clientData = request.session.get('clientData', False)
    
    gal_session = request.session.get('gallery_password', False)
    gal_pw = request.POST.get('gallery_password',request.GET.get('gallery_password'))

    if request.method == "GET" or request.method == "POST":
        try:
            gallery = Gallery.objects.get(pk=pk)
        except Gallery.DoesNotExist:
            return render(request, "clientphotogallery/clientlanding.html", { "message":"Gallery removed or not found" })
        
        if gallery.archived or not gallery.enabled:
            return render(request, "clientphotogallery/clientlanding.html", { "message":"Gallery removed or not found" })
        
        if not gallery.password:
            #print("Gallery has no password")
            # when gallery has no password, we need to set gallery_password session to some random string simulate client successful login
            request.session['gallery_password']="pRgYwI2t?9&vmB1"
            return render(request, "clientphotogallery/clientgalleryview.html", { "gallery":gallery, "clientData":clientData })
        else:
            
            # if password not provided via POST/GET
            if not gal_pw:
                # and no session
                if not gal_session:
                    # ask to submit password
                    return render(request,"clientphotogallery/clientgalleryauth.html", {
                            "gallery_id":gallery.id, 
                            "gallery_title":gallery.title
                            })
                # but session exist
                else:

capstone/clientphotogallery/templates/clientphotogallery/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Client Photo Gallery</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
  </head>
  <body>
    

    <div class="container mt-4">
    {% block body %} 

    {% endblock body %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

capstone/clientphotogallery/templates/clientphotogallery/clientgalleryauth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Client Photo Gallery</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
  <body>
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <form class="form-example" action="{% url 'clientgalleryview' gallery_id %}" method="post">
            <h3>Gallery password for {{ gallery_title }}:</h3>
            <p></p>
            {% csrf_token %}
            <div class="form-group">
                <div class="input-group mb-3">
                    <input type="text" name="gallery_password" class="form-control" placeholder="Gallery password" aria-label="Gallery password" aria-describedby="button-addon2">
                    <input class="btn btn-outline-secondary" type="submit" value="Send" id="button-addon2">
                </div>
            </div>
        </form>   
        <a href="{% url 'clientlandingview' %}">Cancel</a>          
    </div>
  </body>
  <script>
                    
  </script>
</html>

capstone/clientphotogallery/templates/clientphotogallery/clientlanding.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Client Photo Gallery</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
  <body>
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">    
        <form class="form-example" action="{% url 'clientlandingview' %}" method="post">
            
            <h3>Enter Gallery ID:</h3>
            {% csrf_token %}
            <div class="form-group">
                <div class="input-group mb-3">
                    <input type="text" name="gallery_id" class="form-control" aria-label="Gallery" aria-describedby="button-addon2">
                    <input class="btn btn-outline-secondary" type="submit" value="Send" id="button-addon2">
                </div>
            </div>
            
            {% if message %}
            <h3>{{ gallery_title }} {{ message }}</h3>
            {% endif %}
            
        </form>  
             
    </div>
  </body>
</html>

capstone/clientphotogallery/templates/clientphotogallery/gallerycreate.html
{% extends "clientphotogallery/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<main>
  <div class="container-fluid px-4">
    <h1 class="mt-4">Create New Gallery</h1>  
    <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><a href="{% url 'list' %}">Dashboard</a></li>
      <li class="breadcrumb-item active">New Gallery</li>
    </ol>   
    <div class="form-group">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group col-md-6 mb-0">
            {{ form.title|as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.description|as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            <label for="id_password" class="form-label">{{ form.password.label }}</label>
            <div class="input-group mb-3">
              <input type="text" id="id_password" name="{{ form.password.name }}" class="text input form-control" aria-label="Gallery password" aria-describedby="button-addon2"> 
              <button type="button" class="btn btn-outline-secondary" id="generateRandPw">Generate random</button>
            </div>
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.file_field|as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            <div class="form-check form-check-inline">
              {{ form.enabled|as_crispy_field }}
            </div>  
          </div>
          <button type="submit" class="btn btn-success mb-3">Save</button>
          <a href="{{ view.get_success_url }}" class="btn btn-danger mb-3">Cancel</a>
        </form>
        
    </div>
  </div> 
</main>  
{% endblock body %}

{% block script %}
<script>
  //https://stackoverflow.com/a/1349426
  function makepw(length) {
    var result           = '';
    var characters       = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for ( var i = 0; i < length; i++ ) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
  }
 document.querySelector('#generateRandPw').addEventListener('click', function() {
    
    document.querySelector('#id_password').value = makepw(4) + '-' + makepw(4)
 });
</script>
{% endblock %}

capstone/clientphotogallery/templates/clientphotogallery/gallerydelete.html
{% extends "clientphotogallery/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<main>
  <div class="container-fluid px-4">
     <h1 class="mt-4">Delete Gallery</h1>
     <div class="form-group">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p>Are you sure you want to delete Gallery <strong>{{ object.title }}</strong>?</p>
        <button type="submit" class="btn btn-success mb-3">Delete</button>
        <a href="{{ view.get_success_url }}" class="btn btn-danger mb-3">Cancel</a>
      </form>
    </div>
  </div>
</main>

{% endblock body %}

capstone/clientphotogallery/templates/clientphotogallery/galleryedit.html
{% extends "clientphotogallery/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<main>
  <div class="container-fluid px-4">
    <h1 class="mt-4">Edit Gallery</h1>  
    <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><a href="{% url 'list' %}">Dashboard</a></li>
      <li class="breadcrumb-item active">Edit Gallery</li>
    </ol> 
    <div class="form-group">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group col-md-6 mb-0">
            {{ form.title|as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.description|as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            <label for="id_password" class="form-label">{{ form.password.label }}</label>
            <div class="input-group mb-3">
              <input type="text" id="id_password" name="{{ form.password.name }}" class="text input form-control" value="{{ form.password.value}}" aria-label="Gallery password" aria-describedby="button-addon2"> 
              <button type="button" class="btn btn-outline-secondary" id="generateRandPw">Generate random</button>
            </div>
          </div>
          <div class="form-group col-md-6 mb-0">
            <div id="div_id_file_field" class="mb-3">
              <label for="id_file_field" class="form-label">Upload additional files</label>
              <div>
                <input type="file" name="file_field" class="form-control" multiple="" id="id_file_field">
              </div>
            </div>
          </div>
          <div class="form-group col-md-6 mb-0">
            <div class="form-check form-check-inline">
              {{ form.enabled|as_crispy_field }}
            </div>
            <div class="form-check form-check-inline">
              {{ form.archived|as_crispy_field }}
            </div>
          </div>
          <button type="submit" class="btn btn-success mb-3">Save</button>
          <a href="{{ view.get_success_url }}" class="btn btn-danger mb-3">Cancel</a>
        </form>
        
    </div>
  </div> 
</main>  
{% endblock body %}

{% block script %}
<script>
  //https://stackoverflow.com/a/1349426
  function makepw(length) {
    var result           = '';
    var characters       = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for ( var i = 0; i < length; i++ ) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
  }
 document.querySelector('#generateRandPw').addEventListener('click', function() {
    document.querySelector('#id_password').value = makepw(4) + '-' + makepw(4)
 });
</script>
{% endblock %}

capstone/clientphotogallery/templates/clientphotogallery/login.html
{% extends "clientphotogallery/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<h2>Log In</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy}}
  <button type="submit">Log In</button>
</form>

{% endblock %}

capstone/clientphotogallery/templates/clientphotogallery/register.html
{% extends 'clientphotogallery/base.html' %} 
{% load crispy_forms_tags %}

{% block body %}
<h2>Register</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Register</button>
</form>

{% endblock %}